name: Check for Updates and Deploy Status

on:
  schedule:
    - cron: '0 * * * *'  # This runs every hour (adjust as needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Check for Repository Updates
      run: |
        git fetch origin main
        LOCAL_COMMIT=$(git rev-parse HEAD)
        REMOTE_COMMIT=$(git rev-parse origin/main)
        
        if [ "$LOCAL_COMMIT" != "$REMOTE_COMMIT" ]; then
          echo "Changes found, updating status file."
          # Pull the latest changes
          git pull origin main
          
          # Get the latest commit message
          DATE=$(date "+%B %d, %Y")
          CHANGELOG=$(git log -1 --pretty=%B)

          # Update status/index.html
          sed -i "s/<!--LAST_UPDATED_DATE-->/${DATE}/" status/index.html
          sed -i "s/<!--CHANGELOG-->/${CHANGELOG}/" status/index.html

          # Commit and push the changes to the repository
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add status/index.html
          git commit -m "Automatic status update"
          git push origin main
        else
          echo "No changes detected."
        fi
