name: Update Last Updated Info

on:
  push:
    branches:
      - main

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Generate Changelog
      run: |
        DATE=$(date "+%B %d, %Y")
        CHANGELOG=$(git log -1 --pretty=%B)
        sed -i "s/<!--LAST_UPDATED_DATE-->/\${DATE}/" status/index.html
        sed -i "s/<!--CHANGELOG-->/\${CHANGELOG}/" status/index.html


    - name: Commit Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add status/index.html
        git commit -m "Update Last Updated Info"

    - name: Push Changes
      run: |
        git push
